server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://39.103.176.82:3306/library?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: library
    password: gaber123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true